default: &default
  adapter: postgresql
  encoding: unicode
  username: device_root
  password: device_password
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: devices_management_development

test:
  <<: *default
  database: devices_management_test

production:
  <<: *default
  database: devices_management_production
  username: devices_management
  password: <%= ENV['DEVICES_MANAGEMENT_DATABASE_PASSWORD'] %>
